name: Vorvick Productions
favicon: null
layout_spectrum: 0.00803
typography_spectrum: 0.66666
title: "Vorvick Productions: Portland's Metaphoric Game Studio"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#292b27'
    - '#7690a9'
    - '#d4d8db'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
