name: Vorvick Productions
favicon: null
layout_spectrum: 0.578749286243692
typography_spectrum: 0.37869873037561774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.011747581651434302
  lightness: 0.5211419952102005
  saturation: 0.6743105403147638
  rhythmicContrast: 0.6501667292322963
purpose: []
